version: '3.8'

services:
  db:
    image: "platform/postgres"
    build:
      context: ./postgres
      dockerfile: Dockerfile
    hostname: db
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "127.0.0.1:5432:5432"
  user-service:
    image: platform/user-service
    build:
      context: ../components/services/user-service/implementation
      dockerfile: Dockerfile
    hostname: user-service
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - DB_HOSTNAME=db
    depends_on:
      db:
        condition: service_started